// Surface réutilisée par le worker (CDC 14.1 : le worker réutilise les modules NestJS de l'API).
export { AppModule, FEATURE_MODULES, type AppModuleOptions } from './app.module.js';
export { createApp } from './bootstrap.js';
export { Clock, FixedClock, SystemClock } from './common/clock.js';
export { APP_ENV, loadEnv, type AppEnv } from './infra/env.js';
export { InfraModule } from './infra/infra.module.js';
export { PrismaService } from './infra/prisma.service.js';
export { AuditService } from './infra/audit.service.js';
export { ObjectStorage } from './infra/storage.service.js';
export { AttachmentsService } from './modules/attachments/attachments.service.js';
export { SessionService } from './modules/auth/session.service.js';
export { AlertsCoreModule } from './modules/alerts/alerts-core.module.js';
export { AlertsService } from './modules/alerts/alerts.service.js';
export { NotificationsModule } from './modules/notifications/notifications.module.js';
export { NotificationsService, type DailyDigestResult, type DeliveryDecision } from './modules/notifications/notifications.service.js';
export { redactDeliveryError } from './domain/notification-rules.js';
export { JobsModule } from './modules/jobs/jobs.module.js';
export { JobsService, JobAbortedError, type JobHandler, type JobRunOutcome } from './modules/jobs/jobs.service.js';
export { ReportsModule } from './modules/reports/reports.module.js';
export { ReportExportJobHandler } from './modules/reports/export/report-export.job-handler.js';
export { REPORT_EXPORT_JOB } from './modules/reports/export/report-export.service.js';
export { ImportRetentionService, IMPORT_ABANDON_AFTER_DAYS, IMPORT_DATA_RETENTION_DAYS, type ImportRetentionResult } from './modules/imports/import-retention.service.js';
// Worker : traitements planifiés (rattrapage des alertes, outbox e-mail, récapitulatif, purge) et transfert.
export { AccessControlModule } from './modules/access-control/access-control.module.js';
export { AuthModule } from './modules/auth/auth.module.js';
export { IdempotencyService } from './common/idempotency.service.js';
export { describeErrorSafely } from './common/secret-redaction.js';
export { localDate } from './domain/civil-date.js';
export { WORKER_HEARTBEAT_STALE_MS, workerHeartbeatFreshness } from './domain/worker-heartbeat.js';
export { OUTBOX_DEFAULT_MAX_ATTEMPTS, OUTBOX_LOCK_MS, OUTBOX_RETRY_DELAYS_MINUTES, outboxFailureOutcome, outboxLockUntil, outboxRetryDelayMinutes, type OutboxFailureOutcome } from './domain/outbox-retry.js';
export { DAY_MS, MINUTE_MS, catchUpPeriodMs, scheduledRunKey, slotStart } from './domain/job-schedule.js';
export { SettingsService } from './modules/settings/settings.service.js';
export { MaintenancePlansService } from './modules/maintenance/maintenance-plans.service.js';
export { DocumentsService } from './modules/documents/documents.service.js';
export { OdometerFreshnessService } from './modules/odometer/odometer-freshness.service.js';
export { UsagesService } from './modules/usages/usages.service.js';
export { ReservationsService } from './modules/reservations/reservations.service.js';
export { ImmobilizationsService } from './modules/immobilizations/immobilizations.service.js';
export { IncidentsService } from './modules/incidents/incidents.service.js';
export { EMAIL_CHANNEL_NOT_CONFIGURED } from './modules/notifications/notifications.service.js';
